openapi: 3.0.0
info:
  title: Looking Glass API
  version: 1.0.1
servers:
  - url: /
paths:
  /api/logs:
    get:
      operationId: logs_get
      summary: Get all logs
      x-openapi-router-controller: app.openapi_server.controllers.log_controller
      responses:
        "200":
          description: List of daily logs
    post:
      operationId: logs_post
      summary: Create a new daily log
      x-openapi-router-controller: app.openapi_server.controllers.log_controller
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DailyLog"
      responses:
        "201":
          description: Log created

  /api/logs/{date}:
    get:
      operationId: logs_date_get
      summary: Get log by date
      x-openapi-router-controller: app.openapi_server.controllers.log_controller
      parameters:
        - in: path
          name: date
          required: true
          explode: false
          style: simple
          schema:
            type: string
            format: date
      responses:
        "200":
          description: Log found
        "404":
          description: Not found

    put:
      operationId: logs_date_put
      summary: Update log by date
      x-openapi-router-controller: app.openapi_server.controllers.log_controller
      parameters:
        - in: path
          name: date
          required: true
          explode: false
          style: simple
          schema:
            type: string
            format: date
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DailyLog"
      responses:
        "200":
          description: Log updated

    delete:
      operationId: logs_date_delete
      summary: Delete log by date
      x-openapi-router-controller: app.openapi_server.controllers.log_controller
      parameters:
        - in: path
          name: date
          required: true
          explode: false
          style: simple
          schema:
            type: string
            format: date
      responses:
        "204":
          description: Deleted

components:
  schemas:
    DailyLog:
      title: DailyLog
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        title:
          type: string
        entries:
          type: string
        log_date:
          type: string
          format: date
        tags:
          type: array
          items:
            type: string
        mood:
          type: string
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
      example:
        id: "c4a3b180-4569-4b2f-abc2-b84c90a680aa"
        title: "Monday"
        entries: "• Wrote FastAPI router\n• Cleaned controllers"
        log_date: "2025-07-08"
        tags: ["work", "api", "python"]
        mood: "productive"
        created_at: "2025-07-08T08:00:00Z"
        updated_at: "2025-07-08T08:30:00Z"
